// Karma configuration
// Generated on Tue May 14 2013 20:28:21 GMT+0100 (GMT Daylight Time)

//NOTES:
// generated by command line "karma install karma.conf.js"
// run using "karma start karma.conf.js"

// base path, that will be used to resolve files and exclude
basePath = './TestScripts/';


// list of files / patterns to load in the browser
files = [
  JASMINE,
  JASMINE_ADAPTER,
  '../Scripts/External/jquery-1.9.1.js',
  '../Scripts/External/jquery-ui-1.10.2.js',
  '../Scripts/External/underscore.js',
  '../Scripts/External/Angular/angular.js',
  '../Scripts/External/Angular/angular-mocks.js',
  '../Scripts/External/Bootstrap/bootstrap.js',
  '../Scripts/External/Angular-Bootstrap/ui-bootstrap-tpls-0.2.0.js',
  '../Scripts/scrumBoardApp.js',
  '../Scripts/Shared/global.js',
   '../Scripts/models.js',
  '*.js'
];


// list of files to exclude
exclude = [
  
];


// test results reporter to use
// possible values: 'dots', 'progress', 'junit'
reporters = ['progress'];


// web server port
port = 9876;


// cli runner port
runnerPort = 9100;


// enable / disable colors in the output (reporters and logs)
colors = true;


// level of logging
// possible values: LOG_DISABLE || LOG_ERROR || LOG_WARN || LOG_INFO || LOG_DEBUG
logLevel = LOG_INFO;


// enable / disable watching file and executing tests whenever any file changes
autoWatch = true;


// Start these browsers, currently available:
// - Chrome
// - ChromeCanary
// - Firefox
// - Opera
// - Safari (only Mac)
// - PhantomJS
// - IE (only Windows)
browsers = ['Chrome'];


// If browser does not capture in given timeout [ms], kill it
captureTimeout = 60000;


// Continuous Integration mode
// if true, it capture browsers, run tests and exit
singleRun = false;
